openapi: 3.0.3
info:
  title: AI-Powered Todo Chatbot API
  description: API for interacting with the AI-powered todo chatbot
  version: 1.0.0
servers:
  - url: https://kiran-ahmed-todo-phase-3.hf.space
    description: Deployment server
paths:
  /api/{user_id}/chat:
    post:
      summary: Process natural language chat message
      description: Send a natural language message to the AI agent and receive a response
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                conversation_id:
                  type: integer
                  description: Optional conversation ID to continue existing conversation
                message:
                  type: string
                  description: The natural language message from the user
              required:
                - message
      responses:
        '200':
          description: Successful response from the AI agent
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversation_id:
                    type: integer
                    description: The ID of the conversation
                  response:
                    type: string
                    description: The AI agent's response to the user
                  tool_calls:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: The name of the MCP tool called
                        arguments:
                          type: object
                          description: Arguments passed to the MCP tool
        '401':
          description: Unauthorized - invalid or missing JWT token
        '422':
          description: Unprocessable Entity - invalid request parameters
        '500':
          description: Internal Server Error
      security:
        - bearerAuth: []

  /api/auth/signup:
    post:
      summary: User registration
      description: Register a new user account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
              required:
                - email
                - password
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user_id:
                    type: string
        '400':
          description: Bad Request - invalid registration data
        '409':
          description: Conflict - user already exists

  /api/auth/signin:
    post:
      summary: User login
      description: Authenticate user and return JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: User authenticated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: JWT access token
                  token_type:
                    type: string
                    description: Token type (usually "bearer")
        '401':
          description: Unauthorized - invalid credentials

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT